name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # main 브랜치에 코드 푸시할 때 실행됨

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: autopython-452704

      - name: Build and Push Docker Image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/autopython-452704/my-container .
          docker push gcr.io/autopython-452704/my-container

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-container \
            --image=gcr.io/autopython-452704/my-container \
            --region=asia-northeast3 \
            --platform=managed \
            --allow-unauthenticated
