name: Deploy to Cloud Run

on:
  push:
    branches:
      - main   # main 브랜치에 Push될 때 실행 (원하는 브랜치 변경 가능)
  schedule:
    - cron: "30 23 * * *"  # 한국시간(KST) 08:30 실행 (UTC 23:30)
  workflow_dispatch:  # 이 줄 추가!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Repository Checkout
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker & Authenticate Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build & Push Docker Image
        run: |
          gcloud builds submit --tag asia-northeast3-docker.pkg.dev/autopython-452704/cloud-run-repo/my-container

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-container \
            --image=asia-northeast3-docker.pkg.dev/autopython-452704/cloud-run-repo/my-container \
            --platform=managed \
            --region=asia-northeast3 \
            --allow-unauthenticated
